name: pdf_to_image
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_image: ^4.1.11
  pdf_image_renderer: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
